# Generated by Django 2.2.12 on 2020-05-11 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('nombre', models.CharField(max_length=30)),
                ('appaterno', models.CharField(max_length=30)),
                ('apmaterno', models.CharField(max_length=30)),
                ('curp', models.CharField(max_length=18)),
                ('tutor', models.CharField(max_length=40)),
                ('matricula', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Numero de Matricula')),
                ('Sexo', models.CharField(choices=[('F', 'Femenino'), ('M', 'Masculino')], default='M', max_length=1)),
                ('fecha_nacimiento', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Gradogrupo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inscrito', models.BooleanField()),
                ('grupo', models.IntegerField(default=1)),
                ('grado', models.CharField(default='A', max_length=1)),
                ('matriculaFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Escuela.Alumno')),
            ],
        ),
    ]
